### ISSUE TITLE
tx failed with storage override and runtime 2200

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/Acala#2590]
reproduce repo with more details:
https://github.com/shunjizhan/runtime-2200-reproduce

**Comment by StrawberryFlavor** [comment]
```
import-storage:
  Sudo:
    Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
```
